### ISSUE TITLE
Sprint capacity planning and tracking

### ISSUE THREAD

**Issue by sunilthota20** [shridhar-tl/jira-assistant#279]
### Checklist before you being

- [X] I am sure that I am already using latest version of Jira Assistant
- [X] I had verified that there are no existing requests with similar suggestion in [issue tracker](https://github.com/shridhar-tl/jira-assistant/issues)
- [X] I had verified that, my query is not answered in [FAQ section of website](https://www.jiraassistant.com/faq)

### How do you use Jira Assistant?

Browser extension

### Are you using cloud version of Jira or self hosted (data center / server) of Jira.

Self hosted (datacenter)

### Version of Jira Assistant

Web

### What browser are you using?

Chrome

### Feature Suggestion

Request to add capacity planning and tracking feature in your tool.
i checked Atlassian plug ins and most of them are paid, kindly do the needful

thanks in advance

### Checklist before you submit

- [X] I have ensured not to paste any confidential information like Jira url, Mail id, etc.
- [X] I have added required screenshots (as necessary)

**Comment by shridhar-tl** [comment]
@sunilthota20 - Thank you for your suggestion. This is already planned for future and already I have done some ground work on this. But deprioritized it a little as no one has ever asked for it and this option is partially available in cloud Jira. Moreover I got held up with other priority activities.

However, if you can provide reference of some tools or screenshots, that would give me a better idea on what would be more helpful for users. You can mail me the details along with any suggestions / ideas you have and I will plan for that.

**Comment by sunilthota20** [comment]
Thanks @shridhar-tl , here is the reference plug in. It is cost so i am looking for free add ons,

https://marketplace.atlassian.com/apps/1218151/capacity-tracker?tab=overview&hosting=cloud

**Comment by shridhar-tl** [comment]
Thank you @sunilthota20 for providing this reference. I will have a look and will try to implement it ASAP. However, this is totally a new module and would take some time before this is available. I will update this ticket as and when I have some progress/updates.

**Comment by shridhar-tl** [comment]
Hi All,
While half of the development is over using Sync Fussion components, I realized there are CSP issues with Sync Fussion which is stopping me from using it. Now going back to a different component is a complete rewrite from scratch and hence it would be too much of effort. Hence I am planning to wait and watch for the response from Sync Fussion.

Until a solution is found, this ticket is blocked.

Background of the issue:
https://www.syncfusion.com/feedback/43895/security-conserns-due-to-content-security-policy

**Comment by shridhar-tl** [comment]
Hi All, 
**Just an update:**
Sync Fussion has replied stating this issue would be resolved as part of August release. I will validate the fix and if that is resolved, then I would continue with the development.

**Comment by sunilthota20** [comment]
Hi @shridhar-tl 
Any update on my request?

Thanks,
Sunil
