### ISSUE TITLE
Add the Project Code field in the Worklog Report and include epic links in subtasks

### ISSUE THREAD

**Issue by JellBean88** [shridhar-tl/jira-assistant#302]
### Checklist before you being

- [X] I am sure that I am already using latest version of Jira Assistant
- [X] I had verified that there are no existing requests with similar suggestion in [issue tracker](https://github.com/shridhar-tl/jira-assistant/issues)
- [X] I had verified that, my query is not answered in [FAQ section of website](https://www.jiraassistant.com/faq)

### How do you use Jira Assistant?

Browser extension

### Are you using cloud version of Jira or self hosted (data center / server) of Jira.

Cloud Jira

### Version of Jira Assistant

v2.48

### What browser are you using?

Edge

### Feature Suggestion

Please add the Project Code field in the Worklog Report and include epic links in subtasks
![Project Code   Epic Link](https://github.com/shridhar-tl/jira-assistant/assets/129359612/670ece1d-4609-4b66-9cb0-b770228d28fb)

### Checklist before you submit

- [X] I have ensured not to paste any confidential information like Jira url, Mail id, etc.
- [X] I have added required screenshots (as necessary)

**Comment by shridhar-tl** [comment]
Hi @JellBean88 - I hope my previous answer resolves your concern. Hence closing this ticket. Please feel free to reopen this ticket if you are looking for something else.
