### ISSUE TITLE
Time Tracker not showing up

### ISSUE THREAD

**Issue by Jedrzej94** [shridhar-tl/jira-assistant#336]
### Checklist before you being

- [X] I am sure that I am already using latest version of Jira Assistant
- [X] I had verified that, no similar issues are already reported in [issue tracker](https://github.com/shridhar-tl/jira-assistant/issues)
- [X] I had tried reproducing this issue with with [Web version of Jira Assistant](https://app.jiraassistant.com) to ensure that this issue is not recently fixed and yet to be published
- [X] I had verified that, my query is not answered in [FAQ section of website](https://www.jiraassistant.com/faq)
- [X] I had verified that, my issue is not listed as [known bugs in website](https://www.jiraassistant.com/version-history)

### How do you use Jira Assistant?

Browser extension

### Are you using cloud version of Jira or self hosted (data center / server) of Jira.

Cloud Jira

### Version of Jira Assistant

Latest

### What browser are you using?

Chrome

### What OS are you using? You need not disclose this if you feel it is irr-relevant for your issue.

Windows

### Bug Description

In the latest version of Jira (9.11.2) the Time Tracker doesn't show up anymore. I guess this is because they've changed the layout a bit?

![image](https://github.com/shridhar-tl/jira-assistant/assets/15942408/1496a03c-1be2-4392-a29f-32b49bb7d73c)

The Play/Pause/Stop buttons are not showing up.

### Checklist before you submit

- [X] I have ensured not to paste any confidential information like Jira url, Mail id, etc.
- [X] I have verified my browser console logs and added necessary details (if required)
- [X] I have added required screenshots if the bug is related to UI (as necessary)

**Comment by shridhar-tl** [comment]
Hi @Jedrzej94,
Thank you for reporting this issue. Currently after this recent update, there are no unique id's or classes which can be used to attach these controls for individual issues. This time I have tried to fix it. But not sure when it would again break.

The fix would be available for extension uses as part of upcoming release planned for next week. I will update you once again once changes has been published.

**Comment by Jedrzej94** [comment]
HI @shridhar-tl , any news on that? I have updated my JA to the latest version and sadly the feature is still not there. Is it still in some other branch?

**Comment by shridhar-tl** [comment]
@Jedrzej94 - Unfortunately, by the time updates are published, once again structure is slightly modified and it got broken already. I have already noticed it last month end, however, now, I don't see a reliable way to attach this functionality to boards.

I will wait for some more time to see if I could find a way. Otherwise, I will have to remove this functionality. For now you can think this functionality is not there anymore.

**Comment by talltechdude** [comment]
Hi @shridhar-tl, it looks like the selector has just changed by dropping a dash from the `data-test-id` which you're already using at https://github.com/shridhar-tl/jira-assistant/blob/8006231ac543de26b19026a868122242a242017e/src/content-scripts/jira-board.js#L20
```
    const selector = '#ak-main-content div[data-test-id="platform-board-kit.ui.card.card"]';
```
is now:
```
    const selector = '#ak-main-content div[data-testid="platform-board-kit.ui.card.card"]';
```

Just checking if you didn't have the chance to debug this, or if you're just concerned that it will continue to change and become too burdensome to keep on top of these selector and DOM changes? Its a useful feature for someone who lives on that board page day-in, day-out in the Agile world.
