### ISSUE TITLE
Missing settings in Time tracker tab

### ISSUE THREAD

**Issue by Minior6** [shridhar-tl/jira-assistant#360]
### Checklist before you being

- [X] I am sure that I am already using latest version of Jira Assistant
- [X] I had verified that, no similar issues are already reported in [issue tracker](https://github.com/shridhar-tl/jira-assistant/issues)
- [X] I had tried reproducing this issue with with [Web version of Jira Assistant](https://app.jiraassistant.com) to ensure that this issue is not recently fixed and yet to be published
- [X] I had verified that, my query is not answered in [FAQ section of website](https://www.jiraassistant.com/faq)
- [X] I had verified that, my issue is not listed as [known bugs in website](https://www.jiraassistant.com/version-history)

### How do you use Jira Assistant?

Jira cloud App

### Are you using cloud version of Jira or self hosted (data center / server) of Jira.

Cloud Jira

### Version of Jira Assistant

v4.16.0

### What browser are you using?

Edge

### What OS are you using? You need not disclose this if you feel it is irr-relevant for your issue.

Windows

### Bug Description

Hi!
I tried to turn off custom field added by Jira Assistant to issue view
![image](https://github.com/user-attachments/assets/5d7d1052-80c1-426a-bfba-8b465db5f1d3)

But I couldn't find this option in settings. It looks like I don't have all the setting available.
![image](https://github.com/user-attachments/assets/70abab83-c8e3-40f0-97cb-8241b2a73e63)

I've compared it to screen shot added by someone else to one of the issues reported on this GitHub.
![Jira Assistant 1](https://github.com/user-attachments/assets/879e7d03-b22a-40a9-8493-739d96b43170)

I tried to reinstall the App, I've tired switching form Edge to Chrome and I asked my colleague if those setting are available for him, but he doesn't see them as well.

### Checklist before you submit

- [X] I have ensured not to paste any confidential information like Jira url, Mail id, etc.
- [X] I have verified my browser console logs and added necessary details (if required)
- [X] I have added required screenshots if the bug is related to UI (as necessary)
